language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t e1v1s/docker-react -f Dockerfile.dev .


deploy:
  provider:elasticbeanstalk
  region: "eu-central-1"
  app:"docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-377914877449"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $Access key ID
  secret_access_key:
   secure: "$Secret access key"
